{
 "title": "Application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_requests_total{job=\"app\"}[30s])) * 25",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_request_duration_seconds_sum[30s])) / sum by(path) (rate(http_request_duration_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs: INFO",
   "type": "logs",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"app\"} | json | level = `INFO`"
    }
   ]
  },
  {
   "title": "Logs: WARN",
   "type": "logs",
   "gridPos": { "h": 15, "w": 7, "x": 7, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"app\"} | json | level = `WARN`"
    }
   ]
  },
  {
   "title": "Logs: ERROR",
   "type": "logs",
   "gridPos": { "h": 15, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"app\"} | json | level = `ERROR`"
    }
   ]
  }
 ]
}