route:
  group_by: ['alertname']
  group_interval: 5m
  repeat_interval: 1h
  receiver: "telegram"

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: <TOKEN>
        chat_id: <CHAT_ID>
        message: '{{ template "telegram.message". }}'

templates:
  - './telegram.tmpl'
